blog/urls.py
from django.urls import path, include
from django.contrib import admin
from home.views import home_view, data_table, ItemListView

from support.views import support12
from django.conf.urls.static import static
from django.conf import settings
from home.views import ExportExcelView

urlpatterns = [
    path("", home_view, name='home'),

    path('api/', include('post.api.urls')),

    path("support", support12, name='support'),

    path('examples/', include('examples.urls')),

    path('post/', include('post.urls')),

    path("accounts/", include("allauth.urls")),

    path("admin/", admin.site.urls),

    path('data_table/', data_table, name='data_table'),

    path('data_table/data/', ItemListView),

    path('export/excel/', ExportExcelView.as_view(), name='export-excel'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examples/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('filter/', views.BookFilterView.as_view(), name='filter_book'),
    path('/post/create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
]

post/urls.py
from django.urls import path
from .views import *

app_name = "post"

urlpatterns = [

    path('index/', post_index, name="index"),

    path('create/', post_create, name='create'),



    path('<slug:slug>/', post_detail, name='detail'),

    path('<slug:slug>/update/', post_update, name='update'),

    path('<slug:slug>/delete/', post_delete, name='delete'),
]

examples/models.py
from django.db import models


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

examples/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Book


class BookFilterForm(BSModalForm):
    type = forms.ChoiceField(choices=Book.BOOK_TYPES)

    class Meta:
        fields = ['type']


class BookModelForm(BSModalModelForm):
    publication_date = forms.DateField(
        error_messages={'invalid': 'Enter a valid date in YYYY-MM-DD format.'}
    )

    class Meta:
        model = Book
        exclude = ['timestamp']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

examples/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (
    BookModelForm,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm
)
from .models import Book


class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'type' in self.request.GET:
            qs = qs.filter(book_type=int(self.request.GET['type']))
        return qs


class BookFilterView(BSModalFormView):
    template_name = 'examples/filter_book.html'
    form_class = BookFilterForm

    def form_valid(self, form):
        self.filter = '?type=' + form.cleaned_data['type']
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('index') + self.filter


class BookCreateView(BSModalCreateView):
    template_name = 'partials/header.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('home')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'examples/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('index')


class BookReadView(BSModalReadView):
    model = Book
    template_name = 'examples/read_book.html'


class BookDeleteView(BSModalDeleteView):
    model = Book
    template_name = 'examples/delete_book.html'
    success_message = 'Success: Book was deleted.'
    success_url = reverse_lazy('index')


class SignUpView(BSModalCreateView):
    form_class = CustomUserCreationForm
    template_name = 'examples/signup.html'
    success_message = 'Success: Sign up succeeded. You can now Log in.'
    success_url = reverse_lazy('index')


class CustomLoginView(BSModalLoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'examples/login.html'
    success_message = 'Success: You were successfully logged in.'
    success_url = reverse_lazy('index')


def books(request):
    data = {}
    if request.method == 'GET':
        books = Book.objects.all()
        data['table'] = render_to_string(
            '_books_table.html',
            {'books': books},
            request=request
        )
        return JsonResponse(data)

examples/templates/_books_table.html
<table id="books-table" class="table">
  <thead>
  <tr>
    <th class="text-center" scope="col">#</th>
    <th class="text-center" scope="col">Title</th>
    <th class="text-center" scope="col">Author</th>
    <th class="text-center" scope="col">Type</th>
    <th class="text-center" scope="col">Publication date</th>
    <th class="text-center" scope="col">Pages</th>
    <th class="text-center" scope="col">Price (€)</th>
    <th class="text-center" scope="col">Read / Update / Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for book in books %}
    <tr>
      <th class="text-center" scope="row">{{ forloop.counter }}</th>
      <td class="text-center">{{ book.title }}</td>
      <td class="text-center">{{ book.author }}</td>
      <td class="text-center">{{ book.get_book_type_display }}</td>
      <td class="text-center">{{ book.publication_date }}</td>
      <td class="text-center">{{ book.pages }}</td>
      <td class="text-center">{{ book.price }}</td>
      <td class="text-center">
        <!-- Read book buttons -->
        <button type="button" class="read-book btn btn-sm btn-primary" data-form-url="{% url 'read_book' book.pk %}">
          <span class="fa fa-eye"></span>
        </button>
        <!-- Update book buttons -->
        <button type="button" class="update-book btn btn-sm btn-primary" data-form-url="{% url 'update_book' book.pk %}">
          <span class="fa fa-pencil"></span>
        </button>
        <!-- Delete book buttons -->
        <button type="button" class="delete-book btn btn-sm btn-danger" data-form-url="{% url 'delete_book' book.pk %}">
          <span class="fa fa-trash"></span>
        </button>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

examples/templates/_footer.html
<footer class="footer" style="border-top: 1px solid #eee;">
  <div class="container">
    <p class="text-muted mt-3">django-bootstrap-modal-forms
    </p>
  </div>
</footer>

examples/templates/_header.html
{% load static %}

<!-- Header -->
<header style="border-bottom: 1px solid #eee;">
  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->
  <div class="container">
    <!-- Navbar -->
    <!-- Important: columns can be used directly in navbar since it is d-flex -->
    <nav class="navbar navbar-expand-md navbar-light p-0 py-2">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <h1>
              <a class="nav-link p-0" href="/">django-bootstrap-modal-forms
                <span class="sr-only">(current)</span></a>
            </h1>
          </li>
        </ul>
        <p class="text-muted ml-auto m-0">Created and maintained by
          <a href="https://github.com/trco" target="_blank" style="text-decoration: none;">
            <svg style="margin-bottom: -3px; margin-right: 2px;" viewbox="0 0 64 64" width="16" height="16">
              <path
                stroke-width="0"
                fill="currentColor"
                d="M32 0 C14 0 0 14 0 32 0 53 19 62 22 62 24 62 24 61 24 60 L24 55 C17 57 14 53 13 50 13 50 13 49 11 47 10 46 6 44 10 44 13 44 15 48 15 48 18 52 22 51 24 50 24 48 26 46 26 46 18 45 12 42 12 31 12 27 13 24 15 22 15 22 13 18 15 13 15 13 20 13 24 17 27 15 37 15 40 17 44 13 49 13 49 13 51 20 49 22 49 22 51 24 52 27 52 31 52 42 45 45 38 46 39 47 40 49 40 52 L40 60 C40 61 40 62 42 62 45 62 64 53 64 32 64 14 50 0 32 0 Z"></path>
            </svg>
          </a>
          <a href="https://github.com/trco" target="_blank">trco</a>
        </p>
      </div>
    </nav>
    <!-- End Navbar -->
  </div>
</header>
<!-- End Header -->

examples/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

examples/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- Font awesome CSS -->
      <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <!-- Custom CSS -->
      <style media="screen">
        .invalid {
          color: #dc3545;
          font-size: 80%;
        }
        body {
          display: flex;
          flex-direction: column;
          min-height: 100vh;
        }
        .footer {
          margin: auto 0 0;
          height: 56px;
        }
      </style>
    {% endblock stylesheets %}

    <title>django-bootstrap-modal-forms</title>
  </head>

  <body>

    <!-- Includes -->
    {% include "_header.html" %}

    {% block content %}{% endblock content %}

    <!-- Includes -->
    {% include "_footer.html" %}

    <!-- JavaScript -->
    {% block scripts %}
      <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>

examples/templates/index.html
{% extends 'base.html' %}

{% block content %}

  {% include "_modal.html" %}

  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <p class="text-primary">A jQuery plugin for creating AJAX driven Django forms in Bootstrap modal.</p>
        <h4>
          <strong>1. Signup form</strong>
        </h4>
        <p>Sign up via Bootstrap modal.</p>
        <div class="row">
          <div class="col-12 mb-3">
            <button id="signup-btn" class="btn btn-primary" type="button" name="button">Sign up</button>
          </div>
        </div>
        <h4>
          <strong>2. Login form</strong>
        </h4>
        <p>Log in via Bootstrap modal. Sign up first.</p>
        <div class="row">
          <div class="col-12 mb-3">
            {% if not user.is_anonymous %}
              <span>
                Your are logged in as
                <strong>{{ user }}</strong>.
              </span>
              <a href="{% url 'account_logout' %}" id="logout-btn" class="btn btn-danger" role="button">Log out</a>
            {% else %}
              <button id="login-btn" class="btn btn-primary" type="button" name="button">Log in</button>
            {% endif %}
          </div>

        </div>
        <h4>
          <strong>3. CRUD actions</strong>
        </h4>
        <p>Create, Read, Update and Delete books in Bootstrap modal.</p>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-book-sync" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Synchronous
            </button>
            <button id="create-book-async" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create book - Asynchronous
            </button>
            <button id="filter-book" class="filter-book btn btn-primary" type="button" name="button" data-form-url="{% url 'post:create' %}">
              <span class="fa fa-filter mr-2"></span>Filter books
            </button>
          </div>
          <div class="col-12 mb-3">
          {% if 'type' in request.GET %}
            <p class="filtered-books">Filtered books.</p>
          {% endif %}
          {% include "_books_table.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          // Login
          $("#login-btn").modalForm({
            formURL: "{% url 'account_login' %}"
          });

          //  Signup
          $("#signup-btn").modalForm({
            formURL: "{% url 'account_signup' %}"
          });

          // Create book synchronous
          function createBookSyncModalForm() {
            $("#create-book-sync").modalForm({
                formURL: "{% url 'post:create' %}",
                modalID: "#create-modal"
            });
          }
          createBookSyncModalForm();

          // Create book asynchronous button
          // message
          var asyncSuccessMessageCreate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was created.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          // modal form
          function createBookAsyncModalForm() {
            $("#create-book-async").modalForm({
                formURL: "{% url 'create_book' %}",
                modalID: "#create-modal",
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: true,
                  successMessage: asyncSuccessMessageCreate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
            });
          }
          createBookAsyncModalForm();

          // Update book asynchronous button
          // message
          var asyncSuccessMessageUpdate = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          // modal form
          function updateBookModalForm() {
            $(".update-book").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessageUpdate,
                  dataUrl: "books/",
                  dataElementId: "#books-table",
                  dataKey: "table",
                  addModalFormFunction: reinstantiateModalForms
                }
              });
            });
          }
          updateBookModalForm();

          // Delete book buttons - formURL is retrieved from the data of the element
          function deleteBookModalForm() {
            $(".delete-book").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
            });
          }
          deleteBookModalForm();

          // Read book buttons
          function readBookModalForm() {
            $(".read-book").each(function () {
                $(this).modalForm({formURL: $(this).data("form-url")});
            });
          }
          readBookModalForm();

          function reinstantiateModalForms() {
            createBookAsyncModalForm();
            readBookModalForm();
            updateBookModalForm();
            deleteBookModalForm();
          }

          // Filter books button
          $("#filter-book").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}